[2022-07-15 21:15:32,848] - [INFO] - [websocket open]
[2022-07-15 21:15:32,956] - [ERROR] - [now status is WebsocketStatus.STATE_START_WAITING receive error resp {"resp_type":"ERROR","trace_id":"51fe2359-41ca-4bc6-a6d2-814372ec732e","error_code":"SIS.0032","error_msg":"'audio_format' is invalid"}]
[2022-07-15 21:15:32,957] - [INFO] - [websocket close]
[2022-07-15 21:15:32,965] - [ERROR] - [status WebsocketStatus.STATE_CLOSE can't send binary data]
[2022-07-15 21:18:04,057] - [INFO] - [websocket open]
[2022-07-15 21:18:04,122] - [ERROR] - [now status is WebsocketStatus.STATE_START_WAITING receive error resp {"resp_type":"ERROR","trace_id":"58469d75-1486-47fb-b067-767ce7a9132f","error_code":"SIS.0032","error_msg":"'audio_format' is invalid"}]
[2022-07-15 21:18:04,123] - [INFO] - [websocket close]
[2022-07-15 21:18:04,131] - [ERROR] - [status WebsocketStatus.STATE_CLOSE can't send binary data]
[2022-07-15 21:24:45,366] - [INFO] - [websocket open]
[2022-07-15 21:24:47,951] - [INFO] - [websocket close]
[2022-08-07 13:36:11,624] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]
[2022-08-16 20:27:41,959] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107d45c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:27:41,963] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107d45ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:27:41,965] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107d45c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:27:41,968] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107d45ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:27:41,973] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107d45f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:27:41,973] - [ERROR] - [POST Response is empety, url is https://sis-ext.cn-east-3.myhuaweicloud.com/v1/a7b20cfec1f948dbb4a9d145456b21d7/tts]
[2022-08-16 20:30:18,418] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/asr/short-audio (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112c45a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:30:18,420] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/asr/short-audio (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112c45a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:30:18,423] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/asr/short-audio (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112c45a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:30:18,425] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/asr/short-audio (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112c45a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:30:18,428] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/asr/short-audio (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112c45a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:30:18,428] - [ERROR] - [POST Response is empety, url is https://sis-ext.cn-east-3.myhuaweicloud.com/v1/a7b20cfec1f948dbb4a9d145456b21d7/asr/short-audio]
[2022-08-16 20:31:10,115] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112614c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:31:10,118] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112614ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:31:10,120] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112614c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:31:10,123] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112614ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:31:10,126] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is HTTPSConnectionPool(host='sis-ext.cn-east-3.myhuaweicloud.com', port=443): Max retries exceeded with url: /v1/a7b20cfec1f948dbb4a9d145456b21d7/tts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x112614d60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))]
[2022-08-16 20:31:10,127] - [ERROR] - [POST Response is empety, url is https://sis-ext.cn-east-3.myhuaweicloud.com/v1/a7b20cfec1f948dbb4a9d145456b21d7/tts]
[2022-08-16 20:32:27,594] - [ERROR] - [Error occurs in POST, the client will retry 5 times. Error message is ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]
